"use client";
import { useEffect,useMemo,useState } from "react";
import { ArrowDownToLine,ArrowUpFromLine,Boxes,Camera,ClipboardList,Gem,History,ListFilter,Plus,Search,ShieldCheck,Trash2,UserRound,X } from "lucide-react";

type Order={id:number;orderType:string;quantity:number;clientName:string;phone:string;address:string;deliveryDate?:string;specifications:string;finish:string;status:string;advance:number;balance:number;total:number;contactMethod:string;specialCross:string;notes:string};
type Material={id:number;materialType:string;name:string;quantity:number;unit:string;photoUrl:string;notes:string};
type Relic={id:number;title:string;orderType:string;clientName:string;description:string;photoUrl:string};
type Movement={id:number;materialId:number;materialName:string;movementType:string;quantity:number;unit:string;reason:string;movementDate:string};
type SessionUser={email:string;name:string;role:"Consulta"|"Operador"|"Administrador"};
type AppUser={id:number;email:string;name:string;role:SessionUser["role"];active:boolean};
const TYPES=["Lazos de boda","Rosarios completos","Decenarios","Pulseras rosario","Llaveros","Pulseras rosario premium","Otro"];
const STATUSES=["Pendiente","En diseño","En producción","Esperando material","Listo para entregar","Entregado","Cancelado"];
const money=(n:number)=>new Intl.NumberFormat("es-GT",{style:"currency",currency:"GTQ"}).format(n||0);
const blankOrder={orderType:"Rosarios completos",quantity:1,clientName:"",phone:"",address:"",deliveryDate:"",specifications:"",finish:"Dorado",status:"Pendiente",advance:0,balance:0,total:0,contactMethod:"WhatsApp",specialCross:"",notes:""};
const blankMaterial={materialType:"Flores",name:"",quantity:0,unit:"unidades",photoUrl:"",notes:""};
const blankRelic={title:"",orderType:"Rosarios completos",clientName:"",description:"",photoUrl:""};

export default function Home(){
 const [tab,setTab]=useState("pedidos"),[orders,setOrders]=useState<Order[]>([]),[materials,setMaterials]=useState<Material[]>([]),[relics,setRelics]=useState<Relic[]>([]),[movements,setMovements]=useState<Movement[]>([]),[session,setSession]=useState<SessionUser|null>(null),[users,setUsers]=useState<AppUser[]>([]);
 const [modal,setModal]=useState(""),[clientQuery,setClientQuery]=useState(""),[type,setType]=useState("Todos"),[status,setStatus]=useState("Todos"),[deliveryDate,setDeliveryDate]=useState(""),[sortOrder,setSortOrder]=useState("recientes"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [orderForm,setOrderForm]=useState<any>(blankOrder),[materialForm,setMaterialForm]=useState<any>(blankMaterial),[relicForm,setRelicForm]=useState<any>(blankRelic),[movementForm,setMovementForm]=useState<any>({materialId:0,movementType:"Entrada",quantity:1,reason:"",movementDate:new Date().toISOString().slice(0,10)}),[userForm,setUserForm]=useState<any>({email:"",name:"",role:"Consulta"});
 const load=async()=>{try{const sr=await fetch("/api/session");if(!sr.ok){setError("Esta cuenta no está autorizada para usar la aplicación.");return}const su=(await sr.json()).user as SessionUser;setSession(su);const [a,b,c,d]=await Promise.all(["orders","materials","relics","inventory-movements"].map(x=>fetch(`/api/${x}`)));if(!a.ok)throw new Error();setOrders((await a.json()).orders);setMaterials((await b.json()).materials);setRelics((await c.json()).relics);setMovements((await d.json()).movements);if(su.role==="Administrador"){const ur=await fetch("/api/users");if(ur.ok)setUsers((await ur.json()).users)}}catch{setError("No fue posible cargar la información. Intente de nuevo.")}};
 useEffect(()=>{load();if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{})},[]);
 const filtered=useMemo(()=>orders.filter(o=>(type==="Todos"||o.orderType===type)&&(status==="Todos"||o.status===status)&&(!deliveryDate||o.deliveryDate===deliveryDate)&&(`${o.clientName} ${o.phone}`.toLowerCase().includes(clientQuery.toLowerCase()))),[orders,type,status,deliveryDate,clientQuery]);
 const consultationResults=useMemo(()=>[...filtered].sort((a,b)=>{if(sortOrder==="todos")return b.id-a.id;const ad=a.deliveryDate||"0000-00-00",bd=b.deliveryDate||"0000-00-00";return sortOrder==="recientes"?bd.localeCompare(ad):ad.localeCompare(bd)}),[filtered,sortOrder]);
 const upload=async(file:File)=>{const fd=new FormData();fd.append("file",file);const r=await fetch("/api/upload",{method:"POST",body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error);return j.url};
 const post=async(path:string,body:any,method="POST")=>{const r=await fetch(path,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo guardar")};
 const saveOrder=async(e:any)=>run(async()=>{await post("/api/orders",{...orderForm,quantity:+orderForm.quantity,advance:+orderForm.advance,balance:+orderForm.balance,total:+orderForm.total},orderForm.id?"PATCH":"POST");setOrderForm(blankOrder)} ,e);
 const saveMaterial=async(e:any)=>run(async()=>{let photoUrl=materialForm.photoUrl;const file=e.currentTarget.photo.files[0];if(file)photoUrl=await upload(file);await post("/api/materials",{...materialForm,quantity:+materialForm.quantity,photoUrl});setMaterialForm(blankMaterial)},e);
 const saveRelic=async(e:any)=>run(async()=>{const file=e.currentTarget.photo.files[0];if(!file)throw new Error("Agregue una fotografía");await post("/api/relics",{...relicForm,photoUrl:await upload(file)});setRelicForm(blankRelic)},e);
 const saveMovement=async(e:any)=>run(async()=>{await post("/api/inventory-movements",{...movementForm,materialId:+movementForm.materialId,quantity:+movementForm.quantity});setMovementForm({materialId:0,movementType:"Entrada",quantity:1,reason:"",movementDate:new Date().toISOString().slice(0,10)})},e);
 const saveUser=async(e:any)=>run(async()=>{await post("/api/users",userForm,userForm.id?"PATCH":"POST");setUserForm({email:"",name:"",role:"Consulta"})},e);
 const toggleUser=async(u:AppUser)=>{await post("/api/users",{...u,active:!u.active},"PATCH");await load()};
 async function run(action:()=>Promise<void>,e:any){e.preventDefault();setBusy(true);setError("");try{await action();setModal("");await load()}catch(err:any){setError(err.message||"No se pudo guardar") }finally{setBusy(false)}}
 const remove=async(kind:string,id:number)=>{if(!confirm("¿Desea eliminar este registro?"))return;await fetch(`/api/${kind}?id=${id}`,{method:"DELETE"});await load()};
 const addForTab=()=>setModal(tab==="pedidos"?"order":tab==="materiales"?"material":tab==="usuarios"?"user":"relic");
 const heading=tab==="pedidos"?["Control de pedidos","Organice cada pieza desde la solicitud hasta la entrega."]:tab==="materiales"?["Inventario de materiales","Registre entradas, salidas y existencias de cada material."]:tab==="reliquias"?["Reliquias producidas","Conserve una memoria visual de cada creación terminada."]:tab==="usuarios"?["Control de usuarios","Agregue personas y administre sus permisos de acceso."]:["Consultas","Localice pedidos por cliente, reliquia y fecha de entrega."];
 const pending=orders.filter(o=>!["Entregado","Cancelado"].includes(o.status)).length,low=materials.filter(m=>m.quantity<=5).length;
 return <main>
  <header><div className="brand"><img className="appIcon" src="/logo-little-flower-192.png" alt="Logo Rosarios Little Flower"/><div><b>Rosarios Little Flower</b><small>{session?`${session.email} · ${session.role}`:"Pedidos y producción"}</small></div></div>{tab!=="consultas"&&session?.role!=="Consulta"&&<button className="primary" onClick={addForTab}><Plus/>Agregar</button>}</header>
  <nav>{[["pedidos","Pedidos",ClipboardList],["materiales","Inventario",Boxes],["reliquias","Reliquias",Gem],["consultas","Consultas",ListFilter],...(session?.role==="Administrador"?[["usuarios","Usuarios",UserRound]]:[])].map(([id,label,Icon]:any)=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon/>{label}</button>)}</nav>
  <section className="wrap"><div className="welcome"><div><p>ROSARIOS LITTLE FLOWER</p><h1>{heading[0]}</h1><span>{heading[1]}</span></div><img className="welcomeLogo" src="/logo-little-flower-512.png" alt="Rosarios Little Flower"/></div>
  {error&&<div className="error">{error}<button onClick={()=>setError("")}><X/></button></div>}
  {tab==="pedidos"&&<><div className="stats"><article><small>Pedidos activos</small><strong>{pending}</strong></article><article><small>Total registrado</small><strong>{orders.length}</strong></article><article><small>Saldo pendiente</small><strong>{money(orders.reduce((s,o)=>s+Number(o.balance),0))}</strong></article></div><div className="filterTitle"><div><Search/><b>Consulta de pedidos</b></div><button onClick={()=>{setClientQuery("");setType("Todos");setStatus("Todos");setDeliveryDate("")}}>Limpiar filtros</button></div><div className="filters"><Field label="Cliente o teléfono"><label className="search"><Search/><input placeholder="Nombre o teléfono" value={clientQuery} onChange={e=>setClientQuery(e.target.value)}/></label></Field><Field label="Tipo de reliquia"><select value={type} onChange={e=>setType(e.target.value)}><option>Todos</option>{TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Estatus"><select value={status} onChange={e=>setStatus(e.target.value)}><option>Todos</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Fecha de entrega"><input type="date" value={deliveryDate} onChange={e=>setDeliveryDate(e.target.value)}/></Field></div><p className="results">{filtered.length} resultado(s)</p><div className="orders">{filtered.map(o=><article className="order" key={o.id}><div className="orderTop"><span className="tag">{o.orderType}</span><span className={`status s${STATUSES.indexOf(o.status)}`}>{o.status}</span></div><h3>{o.clientName}</h3><p>{o.quantity} unidad(es) · {o.phone||"Sin teléfono"}</p><p className="delivery">Entrega: <b>{o.deliveryDate?new Date(`${o.deliveryDate}T12:00:00`).toLocaleDateString("es-GT"):"Sin fecha definida"}</b></p><p className="spec">{o.specifications||"Sin especificaciones"}</p><div className="orderBottom"><div><small>Total</small><b>{money(o.total)}</b></div><div><small>Pendiente</small><b>{money(o.balance)}</b></div><button onClick={()=>{setOrderForm(o);setModal("order")}}>Editar</button><button className="trash" onClick={()=>remove("orders",o.id)}><Trash2/></button></div></article>)}{!filtered.length&&<Empty text="No hay pedidos que coincidan con la consulta."/>}</div></>}
  {tab==="materiales"&&<><div className="stats"><article><small>Materiales registrados</small><strong>{materials.length}</strong></article><article><small>Existencia baja</small><strong>{low}</strong></article><article><small>Movimientos</small><strong>{movements.length}</strong></article></div><div className="gallery">{materials.map(m=><article key={m.id}>{m.photoUrl?<img src={m.photoUrl} alt={m.name}/>:<div className="placeholder"><Camera/></div>}<div><span className="tag">{m.materialType}</span><h3>{m.name}</h3><p className={m.quantity<=5?"lowStock":""}><b>{m.quantity}</b> {m.unit} en existencia</p><small>{m.notes}</small><div className="stockActions"><button onClick={()=>{setMovementForm({...movementForm,materialId:m.id,movementType:"Entrada"});setModal("movement")}}><ArrowDownToLine/>Entrada</button><button onClick={()=>{setMovementForm({...movementForm,materialId:m.id,movementType:"Salida"});setModal("movement")}}><ArrowUpFromLine/>Salida</button></div></div><button className="trash floating" onClick={()=>remove("materials",m.id)}><Trash2/></button></article>)}{!materials.length&&<Empty text="Agregue el primer material con su fotografía y existencia inicial."/>}</div><section className="movementHistory"><h2><History/>Historial de movimientos</h2>{movements.length?<div className="movementTable"><div className="movementHead"><b>Fecha</b><b>Material</b><b>Movimiento</b><b>Cantidad</b><b>Motivo</b></div>{movements.map(m=><div key={m.id}><span>{m.movementDate}</span><strong>{m.materialName}</strong><span className={m.movementType==="Entrada"?"in":"out"}>{m.movementType}</span><span>{m.quantity} {m.unit}</span><span>{m.reason||"—"}</span></div>)}</div>:<p className="results">Aún no se han registrado entradas o salidas.</p>}</section></>}
  {tab==="reliquias"&&<div className="relics">{relics.map(r=><figure key={r.id}><img src={r.photoUrl} alt={r.title}/><figcaption><span>{r.orderType}</span><h3>{r.title}</h3><p>{r.clientName}</p><small>{r.description}</small></figcaption><button className="trash floating" onClick={()=>remove("relics",r.id)}><Trash2/></button></figure>)}{!relics.length&&<Empty text="La galería está lista para recibir fotografías de trabajos terminados."/>}</div>}
  {tab==="consultas"&&<><div className="filterTitle"><div><Search/><b>Buscar pedidos</b></div><button onClick={()=>{setClientQuery("");setType("Todos");setStatus("Todos");setDeliveryDate("");setSortOrder("recientes")}}>Limpiar filtros</button></div><div className="filters queryFilters"><Field label="Nombre o teléfono"><label className="search"><Search/><input placeholder="Nombre del cliente" value={clientQuery} onChange={e=>setClientQuery(e.target.value)}/></label></Field><Field label="Tipo de reliquia"><select value={type} onChange={e=>setType(e.target.value)}><option>Todos</option>{TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Fecha de entrega"><input type="date" value={deliveryDate} onChange={e=>setDeliveryDate(e.target.value)}/></Field><Field label="Orden"><select value={sortOrder} onChange={e=>setSortOrder(e.target.value)}><option value="recientes">Más recientes</option><option value="antiguos">Más antiguos</option><option value="todos">Todos</option></select></Field></div><p className="results">{consultationResults.length} resultado(s)</p><div className="queryTable"><div className="queryHead"><b>Cliente</b><b>Tipo de reliquia</b><b>Fecha de entrega</b><b>Estatus</b><b>Teléfono</b></div>{consultationResults.map(o=><div key={o.id}><strong>{o.clientName}</strong><span>{o.orderType}</span><span>{o.deliveryDate?new Date(`${o.deliveryDate}T12:00:00`).toLocaleDateString("es-GT"):"Sin fecha"}</span><span>{o.status}</span><span>{o.phone||"—"}</span></div>)}</div>{!consultationResults.length&&<Empty text="No hay pedidos que coincidan con la consulta."/>}</>}
  {tab==="usuarios"&&<><div className="stats"><article><small>Usuarios adicionales</small><strong>{users.length}</strong></article><article><small>Activos</small><strong>{users.filter(u=>u.active).length}</strong></article><article><small>Administradores base</small><strong>2</strong></article></div><div className="userNotice"><ShieldCheck/><p><b>Administradores autorizados:</b> rainerochoamgt@gmail.com y Sochoa87@gmail.com. Desde aquí puede agregar los próximos usuarios.</p></div><div className="userTable"><div className="userHead"><b>Nombre</b><b>Correo</b><b>Permiso</b><b>Estado</b><b>Acciones</b></div>{users.map(u=><div key={u.id}><span>{u.name||"—"}</span><strong>{u.email}</strong><span>{u.role}</span><span className={u.active?"userActive":"userBlocked"}>{u.active?"Activo":"Bloqueado"}</span><span className="userActions"><button onClick={()=>{setUserForm(u);setModal("user")}}>Editar</button><button onClick={()=>toggleUser(u)}>{u.active?"Bloquear":"Activar"}</button><button className="trash" onClick={()=>remove("users",u.id)}><Trash2/></button></span></div>)}</div>{!users.length&&<Empty text="Agregue aquí el próximo usuario autorizado."/>}</>}
  </section>
  {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal("")}}><div className="modal"><button className="close" onClick={()=>setModal("")}><X/></button><h2>{modal==="order"?(orderForm.id?"Editar pedido":"Nuevo pedido"):modal==="material"?"Nuevo material":modal==="movement"?`${movementForm.movementType} de inventario`:modal==="user"?(userForm.id?"Editar usuario":"Nuevo usuario"):"Nueva reliquia"}</h2><p>Complete los datos principales.</p>{modal==="order"?<OrderForm f={orderForm} set={setOrderForm} save={saveOrder} busy={busy}/>:modal==="material"?<MaterialForm f={materialForm} set={setMaterialForm} save={saveMaterial} busy={busy}/>:modal==="movement"?<MovementForm f={movementForm} set={setMovementForm} save={saveMovement} busy={busy} materials={materials}/>:modal==="user"?<UserForm f={userForm} set={setUserForm} save={saveUser} busy={busy}/>:<RelicForm f={relicForm} set={setRelicForm} save={saveRelic} busy={busy}/>}</div></div>}
 </main>
}
function Field({label,children,wide=false}:any){return <label className={wide?"wide":""}><span>{label}</span>{children}</label>}
function OrderForm({f,set,save,busy}:any){const v=(k:string)=>(e:any)=>set({...f,[k]:e.target.value});return <form className="form" onSubmit={save}><Field label="Tipo de pedido"><select value={f.orderType} onChange={v("orderType")}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Cantidad"><input type="number" min="1" value={f.quantity} onChange={v("quantity")}/></Field><Field label="Cliente"><input required value={f.clientName} onChange={v("clientName")}/></Field><Field label="Teléfono"><input value={f.phone} onChange={v("phone")}/></Field><Field label="Dirección" wide><input value={f.address} onChange={v("address")}/></Field><Field label="Fecha de entrega"><input type="date" value={f.deliveryDate||""} onChange={v("deliveryDate")}/></Field><Field label="Acabado / color"><input value={f.finish} onChange={v("finish")}/></Field><Field label="Flores y especificaciones" wide><textarea value={f.specifications} onChange={v("specifications")}/></Field><Field label="Estatus"><select value={f.status} onChange={v("status")}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Forma de contacto"><input value={f.contactMethod} onChange={v("contactMethod")}/></Field><Field label="Total Q"><input type="number" step=".01" value={f.total} onChange={v("total")}/></Field><Field label="Anticipo Q"><input type="number" step=".01" value={f.advance} onChange={v("advance")}/></Field><Field label="Pendiente Q"><input type="number" step=".01" value={f.balance} onChange={v("balance")}/></Field><Field label="Crucero o cruz especial"><input value={f.specialCross} onChange={v("specialCross")}/></Field><Field label="Notas" wide><textarea value={f.notes} onChange={v("notes")}/></Field><Submit busy={busy} text="Guardar pedido"/></form>}
function MaterialForm({f,set,save,busy}:any){const v=(k:string)=>(e:any)=>set({...f,[k]:e.target.value});return <form className="form" onSubmit={save}><Field label="Tipo de material"><input required value={f.materialType} onChange={v("materialType")}/></Field><Field label="Nombre"><input required value={f.name} onChange={v("name")}/></Field><Field label="Existencia inicial"><input required type="number" min="0" step=".01" value={f.quantity} onChange={v("quantity")}/></Field><Field label="Unidad"><input value={f.unit} onChange={v("unit")}/></Field><Field label="Fotografía" wide><input name="photo" type="file" accept="image/*" capture="environment"/></Field><Field label="Notas" wide><textarea value={f.notes} onChange={v("notes")}/></Field><Submit busy={busy} text="Guardar material"/></form>}
function MovementForm({f,set,save,busy,materials}:any){const v=(k:string)=>(e:any)=>set({...f,[k]:e.target.value});return <form className="form" onSubmit={save}><Field label="Material"><select required value={f.materialId} onChange={v("materialId")}><option value="">Seleccione</option>{materials.map((m:Material)=><option key={m.id} value={m.id}>{m.name} ({m.quantity} {m.unit})</option>)}</select></Field><Field label="Movimiento"><select value={f.movementType} onChange={v("movementType")}><option>Entrada</option><option>Salida</option></select></Field><Field label="Cantidad"><input required type="number" min=".01" step=".01" value={f.quantity} onChange={v("quantity")}/></Field><Field label="Fecha"><input required type="date" value={f.movementDate} onChange={v("movementDate")}/></Field><Field label="Motivo o referencia" wide><textarea placeholder="Compra, uso en pedido, ajuste…" value={f.reason} onChange={v("reason")}/></Field><Submit busy={busy} text={`Registrar ${f.movementType.toLowerCase()}`}/></form>}
function RelicForm({f,set,save,busy}:any){const v=(k:string)=>(e:any)=>set({...f,[k]:e.target.value});return <form className="form" onSubmit={save}><Field label="Nombre de la pieza"><input required value={f.title} onChange={v("title")}/></Field><Field label="Tipo"><select value={f.orderType} onChange={v("orderType")}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Cliente"><input value={f.clientName} onChange={v("clientName")}/></Field><Field label="Fotografía"><input required name="photo" type="file" accept="image/*" capture="environment"/></Field><Field label="Descripción" wide><textarea value={f.description} onChange={v("description")}/></Field><Submit busy={busy} text="Guardar reliquia"/></form>}
function UserForm({f,set,save,busy}:any){const v=(k:string)=>(e:any)=>set({...f,[k]:e.target.value});return <form className="form" onSubmit={save}><Field label="Nombre"><input value={f.name} onChange={v("name")}/></Field><Field label="Correo electrónico"><input required type="email" disabled={!!f.id} value={f.email} onChange={v("email")}/></Field><Field label="Permiso" wide><select value={f.role} onChange={v("role")}><option>Consulta</option><option>Operador</option><option>Administrador</option></select></Field><Submit busy={busy} text="Guardar usuario"/></form>}
function Submit({busy,text}:any){return <button className="primary submit" disabled={busy}>{busy?"Guardando…":text}</button>}
function Empty({text}:any){return <div className="empty"><Gem/><h3>Todo listo para comenzar</h3><p>{text}</p></div>}
